services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /tmp
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL"
      SPRING_DATASOURCE_USERNAME: "RM553708"
      SPRING_DATASOURCE_PASSWORD: "271295"

networks:
  default:
    driver: bridge