CREATE SEQUENCE qualidade_ar_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_QUALIDADE_AR
(	"ID_DADO" INTEGER DEFAULT qualidade_ar_seq.nextval NOT NULL,
     "ID_ESTACAO" NUMBER(*,0) NOT NULL,
     "DATA_HORA" TIMESTAMP (0) NOT NULL,
     "NIVEL_PM2_5" FLOAT(53),
     "NIVEL_PM10" FLOAT(53),
     "CONFIG_ALERTAS_ID_CONFIGURACAO" NUMBER(*,0)
);