name: Continuous Delivery

on:
  push:
    branches: ["main"]

env:
    IMAGE_NAME: live09-dev
    AZURE_WEBAPP_NAME: fiap-live09-dev
jobs:
    build:
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v4

              - name: Setup Java SDK
                uses: actions/setup-java@v4
                with:
                  distribution: 'temurin' 
                  java-version: '21'

              - name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Build and Push container to DockerHub
                uses: docker/build-push-action@v6
                with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
