name: Continuous Delivery

on:
  push:
    branches: ["main"]

env:
    IMAGE_NAME: live09-dev
    AZURE_WEBAPP_NAME_DEV: fiap-live09-dev
    AZURE_WEBAPP_NAME_PRD: fiap-live09-prd

jobs:
    build:
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v4

              - name: Setup Java SDK
                uses: actions/setup-java@v4
                with:
                  distribution: 'temurin' 
                  java-version: '21'

              - name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Build and Push container to DockerHub
                uses: docker/build-push-action@v6
                with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                  
    deploy_dev:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to Azure Web App (DEV)
            id: deploy-to-webapp-dev
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
              publish-profile: ${{ secrets.AZURE_PROFILE_DEV }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'

    deploy_prd:
        runs-on: ubuntu-latest
        needs: deploy_dev
        steps:
          - name: Wait for manual approval
            uses: hmarr/auto-approve-action@v2
            with:
              message: "Confirma el despliegue en PRD."

          - name: Deploy to Azure Web App (PRD)
            id: deploy-to-webapp-prd
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME_PRD }}
              publish-profile: ${{ secrets.AZURE_PROFILE_PRD }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'